### ISSUE TITLE
Mixed primer sets

### ISSUE THREAD

**Issue by Gscorreia89** [mikaells/rRNA_counter#7]
Hi,

We use a 16S primer set with a fixed reverse primer and 4 complementary forward primers: GAGTTTGATCNTGGCTCAG, GAGTTTGATCCTGGCTTAG, GAATTTGATCTTGGTTCAG, GGGTTCGATTCTGGCTCAG. Is it possible to configure run RibDif with mixed primer sets? 

Best Wishes,
Goncalo

**Comment by mikaells** [comment]
Sure, just make your own primer-file with the same format as 'default.primers' and use the -p argument. The primer file should be formatted with a name, the forward primer and thenthe reverse primer, all separated by a tab. RibDif will then run all four separately and tell you how each one works.

The results will reflect a PCR with only one pair at a time. I suspect that you plan to run all four in the same reaction, though, in which case you can assume to amplify the union set of all hits. Note that RibDif allows ambiguous nucleotides (such as your 'N') as well as 1 substitution and 1 insertion, making me think that sets 1, 2 and 3 will give highly similar results. Apart from the hit rate, I think that the species overlap will be a more confusing , though.
 
Anyway, your file should look something like this (assuming the reverse primer is a standard V3V4):

set1	GAGTTTGATCNTGGCTCAG GACTACNNGGGTATCTAATCC
set2	GAGTTTGATCCTGGCTTAG GAGTTTGATCCTGGCTTAG
set3	GAATTTGATCTTGGTTCAG GAATTTGATCTTGGTTCAG
set4	GGGTTCGATTCTGGCTCAG GAGTTTGATCNTGGCTCAG

**Comment by Gscorreia89** [comment]
Hi,

Thanks, I configured the primers as per your suggestion and everything worked nicely. And above all, thanks for putting together this really interesting tool!
